version: '3.8'

services:
  efs-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: efs-app
    restart: always
    ports:
      - "3000:3000"
    volumes:
      # save data faktur di luar container
      - ./faktur_data.json:/app/faktur_data.json
    environment:
      - NODE_ENV=production
