version: '3.8'

services:
  efs-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: efs-app
    restart: always
    ports:
      # Format: "Port_di_Ubuntu:Port_di_Docker"
      # Ubah angka 3000 pertama (sebelah kiri) jika port 3000 sudah dipakai aplikasi lain
      - "3000:3000"
    volumes:
      # Menyimpan data faktur secara permanen di luar container
      - ./faktur_data.json:/app/faktur_data.json
    environment:
      - NODE_ENV=production
