server {
    listen 80;
    server_name _;
    
    # Otomatis alihkan trafik HTTP biasa ke HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name _;

    # Arahkan ke sertifikat yang nanti ada di dalam Docker Nginx
    ssl_certificate /etc/nginx/ssl/eFS-cert.pem;
    ssl_certificate_key /etc/nginx/ssl/eFS-key.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Jika ada yang mengakses IP saja, arahkan otomatis ke /efs
    location = / {
        return 301 https://$host/efs;
    }

    # Teruskan trafik ke container aplikasi Next.js (efs-app)
    location / {
        proxy_pass http://efs-app:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
